### ISSUE TITLE
Moar awesome stuff

### ISSUE THREAD

**Issue by alfonsogarciacaro** [kunjee17/awesome-fable#37]
I'm missing here some of the recent amazing contributions to community. I'd like to show this page during fsharpconf so people know where to find great material to learn and use Fable. This is what I can remember from the top of my head, but please feel free to expand the list.

I'll add this by myself:

- @Zaid-Ajaj Toastr, FlatPickr
- @MangelMaxime HTML to Elmish
- @rommsen Catch-of-the-day

@vbfox Can you please add a link to your Elmish.React tutorials?
@Dzoukr I remember there was a web for Czech elections made with Fable, could you please add a link?

Thank you all in advance for your help!

**Comment by kunjee17** [comment]
@Zaid-Ajaj you guide for react component to Fable would be good addition here too.

**Comment by Dzoukr** [comment]
Here you are my friend.

http://showme.median.cz/volby-2018/

**Comment by rommsen** [comment]
I submitted a PR for the SAFE documentation and my SAFE Confplanner

**Comment by Zaid-Ajaj** [comment]
> your guide for react component to Fable would be good addition here too.

Still WIP and might take a while TBH, I will send a PR when I finish it :smile:

**Comment by StachuDotNet** [comment]
@kunjee17 yeah... OK fine I won't be lazy :) I have it scheduled for Saturday morning.

**Comment by kunjee17** [comment]
@alfonsogarciacaro should I be adding my article on performance of Fable into list? Or Fable 2 gonna cover it and I can skip that?

**Comment by alfonsogarciacaro** [comment]
@kunjee17 Surely add it, please! Sorry I forgot about it 😅 We can revisit the article when Fable 2 is out :)

**Comment by StachuDotNet** [comment]
@alfonsogarciacaro @kunjee17 Are you guys cool if I do a reorganization of the headers and such?

I started to just add the links that I have into the existing structure, but I think that things can be presented better with a bit of work. If you guys are cool with that, I'll submit the final PR late tonight.
( warning to others: please don't fork or PR right now, as merging will be quite annoying for @kunjee17 after if they give the 'yes' to a reorg :) )

**Comment by alfonsogarciacaro** [comment]
Even if I'm too lazy to send PRs and abuse my write rights to edit the README online, @kunjee17 is the creator and maintainer of this repo, so he's the one that must give the OK :)

**Comment by kunjee17** [comment]
@StachuDotNet I'm very much ok... I guess there is no on going PR. So, if feel moving things around please go for it... Basically all links should be there with some arranged manner. And links should be unique...
